name: Баг
description: Описать проблему, чтобы помочь починить её
body:
  - type: textarea
    id: bug_description
    attributes:
      label: Описание бага
      description: Четкое и понятное описание сути бага.
    validations:
      required: true
  - type: textarea
    id: bug_reproduction
    attributes:
      label: Шаги воспроизведения
      description: Опишите способ воспроизведения бага.
      value: |
          Шаги чтобы воспроизвести баг:
          1. 
    validations:
      required: true
  - type: textarea
    id: expected_behaviour
    attributes:
      label: Ожидаемое поведение
      description: Четкое и понятное описание того, что должно было произойти.
    validations:
      required: true
  - type: textarea
    id: additional_info
    attributes:
      label: (Опционально) Характеристики
      description: Здесь можете описать любую дополнительную информацию, которая касается бага. Также можете приложить скриншоты.
      value: |
          - OS: [e.g. Windows/Linux, эмулятор]
          - Версия клиента [смотрите в BYOND]
          - Версия сервера [команда "Show Server Revision" в вкладке ООС на сервере]
          - ID игры [там же]
